server:
  port: 8081
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

canal.conf:
  mode: tcp #tcp kafka rocketMQ rabbitMQ
  flatMessage: true
  zookeeperHosts:
  syncBatchSize: 1000
  retries: -1
  timeout:
  accessKey:
  secretKey:
  consumerProperties:
    # canal tcp consumer
    canal.tcp.server.host: canal:11111
    canal.tcp.zookeeper.hosts:
    canal.tcp.batch.size: 500
    canal.tcp.username:
    canal.tcp.password:
  srcDataSources:
    defaultDS:
      url: jdbc:mysql://canal:3306/sth-clinic-new?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=Asia/Shanghai
      username: root
      password: yskj123456
  canalAdapters:
    - instance: centerDB # canal instance Name or mq topic name
      groups:
        - groupId: g1
          outerAdapters:
#            - name: rdb
#              key: sqlserver11
#              properties:
#                jdbc.driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#                jdbc.url: jdbc:sqlserver://canal:1433;DatabaseName=middleDB_FT
#                jdbc.username: sa
#                jdbc.password: yskj123456
#            - name: rdb
#              key: sqlserver13
#              properties:
#                jdbc.driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#                jdbc.url: jdbc:sqlserver://canal:1433;DatabaseName=middleDB_HP
#                jdbc.username: sa
#                jdbc.password: yskj123456
#            - name: rdb
#              key: sqlserver12
#              properties:
#                jdbc.driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#                jdbc.url: jdbc:sqlserver://canal:1433;DatabaseName=middleDB_FQ
#                jdbc.username: sa
#                jdbc.password: yskj123456
            - name: rdb
              key: mysql02
              properties:
                jdbc.driverClassName: com.mysql.jdbc.Driver
                jdbc.url: jdbc:mysql://canal:3306/centerdb?useUnicode=true
                jdbc.username: root
                jdbc.password: yskj123456
            - name: es7
              key: exampleKey
              hosts: http://canal:9200
              properties:
                mode: rest
                cluster.name: docker-cluster
                security.auth: elastic:es123456     # only used for rest mode
